version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  web:
    container_name: web
    build:
      context: ./
      target: dev
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/postgres?schema=public"
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    links:
      - db
    volumes:
      - './:/src'
volumes:
  db:
    driver: local